### PR TITLE
[CDAP-20224] remove explore references in cdap-ui

### PR DESCRIPTION
**Pull request by sumengwang**
# [CDAP-20224] remove explore references in cdap-ui

## PR Type
- [ ] Bug Fix
- [ ] Feature
- [ ] Build Fix
- [ ] Testing
- [x] General Improvement
- [ ] Cherry Pick

## Links
Jira: [CDAP-20224](https://cdap.atlassian.net/browse/CDAP-20224)

## Test Plan
After removing these references, build is fine. And It doesn't seem we have tests related to explore api

[CDAP-20224]: https://cdap.atlassian.net/browse/CDAP-20224?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CDAP-20224]: https://cdap.atlassian.net/browse/CDAP-20224?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by njbriggs — APPROVED** [review]

**Comment by seanfeld** [comment]
@sumengwang  What did you do to verify that the build is fine after you removed this code?

**Comment by sumengwang** [comment]
> @sumengwang What did you do to verify that the build is fine after you removed this code?

just clicking on each component and see if things still work

**Comment by seanfeld** [comment]
> > @sumengwang What did you do to verify that the build is fine after you removed this code?
> 
> just clicking on each component and see if things still work

Did you run the tests? Please post this pr in the cdap channel when it merges to make everyone aware

**Comment by sumengwang** [comment]
> > > @sumengwang What did you do to verify that the build is fine after you removed this code?
> > 
> > 
> > just clicking on each component and see if things still work
> 
> Did you run the tests? Please post this pr in the cdap channel when it merges to make everyone aware

All cypress and cucumber tests passed

**Review by seanfeld — APPROVED** [review]

**Pull request merged**
