### PR TITLE
Add chrome extension for reporting missing data-testids easily

### PR DESCRIPTION
**Pull request by GnsP**
# Add chrome extension for reporting missing data-testids easily

## Description
Adds a chrome extension, which when enabled, allows the user to view and copy (on click) `data-testid` of any element if present. If the `data-testid` is not present then clicking on the element should open an email with the `cdap-ui-eng` team. 

## PR Type
- [ ] Bug Fix
- [ ] Feature
- [ ] Build Fix
- [x] Testing
- [ ] General Improvement
- [ ] Cherry Pick

## Links
Jira: [CDAP-20975](https://cdap.atlassian.net/browse/CDAP-20975)

## Test Plan
NA

## Screenshots
Screenshot 2024-01-29 at 18 11 12

[CDAP-20975]: https://cdap.atlassian.net/browse/CDAP-20975?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by njbriggs** [comment]
Where is the icon from? We need to make sure there are no licensing issues.

**Comment by GnsP** [comment]
> Where is the icon from? We need to make sure there are no licensing issues.

This is a placeholder icon (png) that I had. As far as I remember I had downloaded it from an opensource icon set. However, I am in favor of replacing this icon with a CDAP icon that we can safely use.

**Comment by njbriggs** [comment]
I'd like to make sure we have an image with known provenance. Everything else LGTM.

**Comment by GnsP** [comment]
> I'd like to make sure we have an image with known provenance. Everything else LGTM.

@njbriggs I have updated the icon. Now we are using the cdap favicon as the icon for the extension.

**Review by njbriggs — APPROVED** [review]

**Review by radhikav1 — APPROVED** [review]

**Pull request merged**
