### PR TITLE
Adds min & max range for pipeline preview records

### PR DESCRIPTION
**Pull request by antony-britto**

### CODE REVIEW

**Comment by njbriggs** [comment]
Is there a Jira for this? Can you add a screenshot?

**Comment by antony-britto** [comment]
image

**Comment by antony-britto** [comment]
Jira link - https://cdap.atlassian.net/browse/CDAP-18668

**Comment by njbriggs** [comment]
I'm wary of using a slider only because it's not as accessible. Can we add a text input? Or just keep the current text input with a range check?

Also, what happens to pipelines that have a value great than 5000? I don't think there are many, but we should know what will happen.

**Comment by antony-britto** [comment]
> I'm wary of using a slider only because it's not as accessible. Can we add a text input? Or just keep the current text input with a range check? 
   > Restored it to existing text input.

> Also, what happens to pipelines that have a value great than 5000? I don't think there are many, but we should know what will happen. 
  > Max limit will be provided by API. UI has a fallback value as 5000 and it will be overridden through an API call.

**Review by seanfeld — COMMENTED** [review]
Code looks fine but does this address @njbriggs 's concerns about accessibility/usability?

**Comment by antony-britto** [comment]
> Code looks fine but does this address @njbriggs 's concerns about accessibility/usability?

i have reverted to the existing text input. Not using range slider anymore.

image

**Review by seanfeld — APPROVED** [review]

**Pull request merged**
